export {default as Dashboard } from './dashboard/Dashboard'
export {default as Developer } from './developer/Developer'
export {default as Login } from './login/Login'
export {default as  Navbar} from './navbar/Navbar'
export {default as Post } from './post/Post'
export {default as Posts } from './posts/Posts'
export {default as Profile } from './profile/Profile'
export {default as Profiles } from './profiles/Porfiles'
export {default as Register } from './register/Register'